name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Clean old reports
        run: |
          if (Test-Path "cypress/reports/html") { Remove-Item -Recurse -Force "cypress/reports/html" }
          if (Test-Path "cypress/reports/final") { Remove-Item -Recurse -Force "cypress/reports/final" }

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate HTML report
        run: npm run posttest

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/final/index.html
